### ISSUE TITLE
hi~想沟通一下插件能否加UA

### ISSUE THREAD

**Issue by tuuna** [cnhongv/typecho-cos-plugin#1]
你好，我是腾讯云COS这边的研发~我们最近在搞生态相关的一些活动，看到您这里有支持typecho的插件，如果您方便的话，想能和您联系一下（邮箱hustxiong(熊建刚) <hustxiong@tencent.com>），希望能在插件中加上typecho的UA。我们可以后续再沟通，打扰您了

**Comment by cnhongv** [comment]
已经增加了

**Comment by tuuna** [comment]
感谢🙏
