### ISSUE TITLE
typecho1.2启用插件后全站白屏

### ISSUE THREAD

**Issue by zhixicn** [cnhongv/typecho-cos-plugin#4]
后台页面及设置一切正常，前台全站白屏。
环境：debian10+nginx1.22+mysql5.7+php8.1

**Comment by daxiyun** [comment]
复议

**Comment by zhixicn** [comment]
您好，邮件已经收到，我会尽快回复。 马光远

**Comment by cnhongv** [comment]
@daxiyun  @zhixicn  好的，明天我测试一下

**Comment by daxiyun** [comment]
> @daxiyun @zhixicn 好的，明天我测试一下

我使用的typecho是GitHub的最新开发版

**Comment by cnhongv** [comment]
@daxiyun @zhixicn 已修复
