### ISSUE TITLE
上传大于3M的文件时上传失败

### ISSUE THREAD

**Issue by Harry-Pan** [cnhongv/typecho-cos-plugin#5]
环境：centos7.6+typecho1.2.0+Nginx 1.20.2+PHP 7.4.29+MariaDB 10.5.15
上传大于3M的附件时实际可以成功上传到存储桶，但是编辑页面提示上传失败。小于3M的附件都可以正常上传使用。
控制台信息：
POST https://www.harrypan.cn/index.php/action/upload?cid=167&_=e17f2583615f7f2cc861fbc5f581c730 500 (Internal Server Error)

**Comment by cnhongv** [comment]
没有复现，建议查看php配置是否设置了脚本超时时间
